#PERSONAL INFORMATIONS:

  #mandatory
CodiceFiscale :  ABCDESKEJAIWNSJI
#optional, leave 0 if you don't have it
TesseraSanitaria : 9898987897987987889
#mandatory, you will recieve the sms for confirming the booking here
Phone : 393198297829
#mandatory only if you have tessera sanitaria (format: 09/07/2021)
BirthDate : 

#FILTERS:

  #the vaccinations centers will be AROUND the place you select, but not only (if you put Milan you can get bookings in Como, etc.)


#enter the range in which you would like to find a booking, extremes will be countend. (format: 09/07/2021)
FirstDose :
  Start : 1/07/2021 
  End :  31/08/2021

#the date of the first dose will determine the date for the second too, so you have to choose now the range for the second dose
SecondDose :
  Start : 1/09/2021
  End : 10/10/2021

 
#TWEAKS:

#delay between each retry (in seconds )
Delay : 0
#range of random seconds to add/subtract to the delay ( for example if delay = 10 and range = 2 , the actual delay will be between 8 and 12 seconds)
Range : 0
#seconds to wait before refreshing (put high if you have bad connection)
Timeout : 5
